language: node_js
dist: trusty
sudo: false

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - yarn global add elm
  - yarn
  - sed -i s/statFix\(/\(/ node_modules/npm/node_modules/graceful-fs/polyfills.js # https://github.com/nodejs/help/issues/2874

script:
  - yarn gitbook
  - yarn example
  - cd example
  - elm make src/Main.elm
  - mkdir ../_book/example
  - mv index.html ../_book/example

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _book
  on:
    branch: master
