language: node_js
dist: trusty
sudo: false

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script: ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _book
  on:
    branch: master
