language: node_js
dist: trusty
sudo: false

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g elm @openapitools/openapi-generator-cli

script:
  - ./build.sh
  - cd example
  - openapi-generator generate -g elm -i swapi.yaml -o generated
  - elm make src/Main.elm
  - mkdir ../_book/example
  - mv index.html ../_book/example

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _book
  on:
    branch: master
